# Generated by Django 6.0.3 on 2026-03-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text='e.g. store@sbi', max_length=255, null=True)),
                ('merchant_name', models.CharField(blank=True, help_text='e.g. Store Name', max_length=255, null=True)),
            ],
        ),
    ]
